"""Generate a ModuleManager patch that labels every part with the mod it comes from.

In game this shows up as:
  * the part description starting with "[Mod: <name>]" (VAB/SPH part info), and
  * the mod's CKAN identifier added to the part's search tags, so typing it in the editor's part
    search lists every part from that mod.

The patch is plain text in its own GameData folder; deleting the folder undoes it.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

from .instance import Instance
from .partindex import GameDataIndex
from .registry import Registry

FOLDER = "zzz_kat_ModTags"
_MM_UNSAFE = re.compile(r"[\[\],|&:@%$!*{}]")  # chars that would break a PART[...] filter
_OLD_LABEL = re.compile(r"^\[Mod: [^\]]*\]\s*")  # our own label, if the index saw a patched cache


def _clean(text: str) -> str:
    """Make a value safe for a single-line ConfigNode value."""
    return " ".join(text.replace("{", "(").replace("}", ")").replace("//", "/ /").split())


def _label(mod: str, reg: Registry) -> tuple[str, str]:
    """(display name, search tag) for an owner string from the index."""
    if mod.startswith("stock:"):
        return ("Stock" if mod == "stock:Squad" else "Stock DLC"), "stock"
    if mod.startswith("manual:"):
        folder = mod.split(":", 1)[1]
        return f"{folder} (manual install)", folder.lower()
    m = reg.modules.get(mod)
    return (m.name if m else mod), mod.lower()


def generate(idx: GameDataIndex, reg: Registry) -> tuple[str, list[str]]:
    """Return (patch text, skipped part names)."""
    lines = [
        "// Generated by kerbal-agent-tools (`kat tag-parts`). Labels each part with its mod.",
        "// Delete this folder to undo. Regenerate after adding/removing mods.",
        "",
    ]
    skipped: list[str] = []
    for p in sorted(idx.parts.values(), key=lambda p: (p.mod, p.name)):
        raw = p.raw_name or p.name
        if _MM_UNSAFE.search(raw):
            skipped.append(p.name)
            continue
        display, tag = _label(p.mod, reg)
        desc = _clean(f"[Mod: {display}] {_OLD_LABEL.sub('', p.description)}")
        tags = _clean(" ".join([t for t in p.tags.split() if t != tag] + [tag]))
        lines += [
            f"@PART[{raw.replace(' ', '?')}]:FINAL",
            "{",
            f"\t%description = {desc}",
            f"\t%tags = {tags}",
            "}",
        ]
    return "\n".join(lines) + "\n", skipped


def install(inst: Instance, idx: GameDataIndex, reg: Registry) -> dict:
    text, skipped = generate(idx, reg)
    folder = inst.gamedata / FOLDER
    folder.mkdir(exist_ok=True)
    path = folder / "ModTags.cfg"
    path.write_text(text, encoding="utf-8")
    return {"installed": str(path), "parts_tagged": len(idx.parts) - len(skipped), "skipped": skipped}


def uninstall(inst: Instance) -> dict:
    folder = inst.gamedata / FOLDER
    existed = folder.exists()
    if existed:
        shutil.rmtree(folder)
    return {"removed": str(folder) if existed else None}
